os: linux
services:
   - docker
sudo: required
language: python
env:
  global:
    - CONAN_REFERENCE="VTK/7.1.0"
    - CONAN_USERNAME="bilke"
    - CONAN_LOGIN_USERNAME="bilke"
    - CONAN_CHANNEL="testing"
    - CONAN_TOTAL_PAGES=4
    - CONAN_STABLE_BRANCH_PATTERN="release/*"
    - CONAN_UPLOAD="https://api.bintray.com/conan/ogs/conan"

  matrix:
    - CONAN_GCC_VERSIONS=4.6 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=1
    - CONAN_GCC_VERSIONS=4.6 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=2
    - CONAN_GCC_VERSIONS=4.6 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=3
    - CONAN_GCC_VERSIONS=4.6 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=4
    - CONAN_GCC_VERSIONS=4.8 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=1
    - CONAN_GCC_VERSIONS=4.8 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=2
    - CONAN_GCC_VERSIONS=4.8 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=3
    - CONAN_GCC_VERSIONS=4.8 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=4
    - CONAN_GCC_VERSIONS=4.9 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=1
    - CONAN_GCC_VERSIONS=4.9 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=2
    - CONAN_GCC_VERSIONS=4.9 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=3
    - CONAN_GCC_VERSIONS=4.9 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=4
    - CONAN_GCC_VERSIONS=5.2 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=1
    - CONAN_GCC_VERSIONS=5.2 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=2
    - CONAN_GCC_VERSIONS=5.2 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=3
    - CONAN_GCC_VERSIONS=5.2 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=4
    - CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=1
    - CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=2
    - CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=3
    - CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=4
    - CONAN_GCC_VERSIONS=5.4 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=1
    - CONAN_GCC_VERSIONS=5.4 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=2
    - CONAN_GCC_VERSIONS=5.4 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=3
    - CONAN_GCC_VERSIONS=5.4 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=4
    - CONAN_GCC_VERSIONS=6.2 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=1
    - CONAN_GCC_VERSIONS=6.2 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=2
    - CONAN_GCC_VERSIONS=6.2 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=3
    - CONAN_GCC_VERSIONS=6.2 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=4

matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      language: generic
      env: CONAN_CURRENT_PAGE=1
    - os: osx
      osx_image: xcode8.2
      language: generic
      env: CONAN_CURRENT_PAGE=2
    - os: osx
      osx_image: xcode8.2
      language: generic
      env: CONAN_CURRENT_PAGE=3
    - os: osx
      osx_image: xcode8.2
      language: generic
      env: CONAN_CURRENT_PAGE=4
    - os: osx
      osx_image: xcode8
      language: generic
      env: CONAN_CURRENT_PAGE=1
    - os: osx
      osx_image: xcode8
      language: generic
      env: CONAN_CURRENT_PAGE=2
    - os: osx
      osx_image: xcode8
      language: generic
      env: CONAN_CURRENT_PAGE=3
    - os: osx
      osx_image: xcode8
      language: generic
      env: CONAN_CURRENT_PAGE=4
    - os: osx
      osx_image: xcode7.3
      language: generic
      env: CONAN_CURRENT_PAGE=1
    - os: osx
      osx_image: xcode7.3
      language: generic
      env: CONAN_CURRENT_PAGE=2
    - os: osx
      osx_image: xcode7.3
      language: generic
      env: CONAN_CURRENT_PAGE=3
    - os: osx
      osx_image: xcode7.3
      language: generic
      env: CONAN_CURRENT_PAGE=4
    - os: osx
      osx_image: xcode7.1
      language: generic
      env: CONAN_CURRENT_PAGE=1
    - os: osx
      osx_image: xcode7.1
      language: generic
      env: CONAN_CURRENT_PAGE=2
    - os: osx
      osx_image: xcode7.1
      language: generic
      env: CONAN_CURRENT_PAGE=3
    - os: osx
      osx_image: xcode7.1
      language: generic
      env: CONAN_CURRENT_PAGE=4

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
